# Case study definition
# name of the case study. The problem formulation and ouptuts will be printed into the following relative path from main directory : case_studies/config['case_study']
'case_study': 'MC_2'
# number of typical days to consider
'nbr_td': 12
# Dictionnary with the dataframes containing all the data in the form : {'Demand': eud, 'Resources': resources, 'Technologies': technologies, 'End_uses_categories': end_uses_categories, 'Layers_in_out': layers_in_out, 'Storage_characteristics': storage_characteristics, 'Storage_eff_in': storage_eff_in, 'Storage_eff_out': storage_eff_out, 'Time_series': time_series, 'Misc': misc}
'all_data': {}

#Criteria limits
#CAUTION : The limits used for criteria normalization (defined in es_model.mod line 164) have to be modify to explore "extreme" scenarios
#REMARK : The weights of criteria can be change in es_model.mod line 159

##### MC parameters ####

'Cost_min': 43;
'LCA_min' : 1;
'Crit_1_min': 130;
'Crit_2_min': 100000;
'Crit_3_min': 10000;

'Cost_max': 150000;
'LCA_max' : 120000;
'Crit_1_max': 700;
'Crit_2_max': 3000000;
'Crit_3_max': 300000;

'Weight_Cost' : 0;
'Weight_LCA' : 0;
'Weight_Crit1' : 0;
'Weight_Crit2' : 0;
'Weight_Crit3' : 0;

'Weight_GWP' : 0;
'GWP_min': 0;
'GWP_max': 10000000;

# Relative path from main directory to energyscope subdirectories and files
'data_dir': 'Data/2030_BE'  # Folders containing the csv data files
'es_path': 'energyscope/energy_model'  # Path to the energy model (.mod and .run files)
'cs_path': 'case_studies' # Path to the directory containing the different case studies
'step1_path': 'energyscope/preprocessing/td_selection' # Path to the step1 selection of typical days

# Printing input files for optimisation model
# printing the data in ETSD_data.dat file for the optimisation problem
printing: True
# printing the time related data in ESTD_12TD.dat for the optimisation problem
printing_td: True

# Run options for optimization problem
# path to AMPL licence directory (to adapt by the user), set to None if AMPL is in your PATH variables
# /!\ Don't use "\" but rather "\\" or "/"
'AMPL_path': 
# options for ampl -> (initialy barconvtol=1e-6)
'ampl_options' : {'show_stats': 3,
                  'log_file': 'output/log.txt',
                  'presolve': 10,
                  'presolve_eps': 1e-7,
                  'presolve_fixeps': 1e-7,
                  'show_boundtol': 0,
                  '_log_input_only': False,
                  'solver': 'gurobi',
                  'gurobi_options' : 'predual=-1 method=2 crossover=0 prepasses=3 barconvtol=1e-6 presolve=-1'
}
# Printing more detailed outputs
'print_barh' : False
'print_hourly_data': False
'print_sankey': False
'save_MC_outputs' : True
